### ISSUE TITLE
Create a Github release for v0.2.0

### ISSUE THREAD

**Issue by sllvn** [jspm/nodelibs-process#4]
On NPM, this is published as `0.2.0`. However, on the tagged releases page (https://github.com/jspm/nodelibs-process/releases), the latest is `0.2.0-alpha`.

Can you create a new Github release for `0.2.0`?

Thanks!

**Comment by guybedford** [comment]
This will be released on Github as stable when jspm 0.17 is released. Until
then these libraries are stable for 0.16.

**Comment by sllvn** [comment]
Gotcha. So is the NPM version at https://www.npmjs.com/package/jspm-nodelibs-process unofficial? The only version published there is `0.2.0` (not alpha).

**Comment by guybedford** [comment]
Yes, those versions are being used for jspm 0.17 as the stable installs in the mean time.
